---

# The language to use in the launcher.
# By default, this is the system language. (en-us)
language: "en-us"

# Launcher general config
launcher:
    # Whether to always elevate the launcher on start up or not.
    #
    # The launcher might sometimes ask for elevation regardless to open the game.
    always-elevate: true

# Game information config
game:
    # The absolute path to the game's executable.
    #
    # This is used to launch the game.
    path: "C:/Program Files/Genshin Impact/Genshin Impact game/GenshinImpact.exe"

    # A list of supported modifications to inject into the game.
    #
    # Valid examples:
    # - 3DMigoto/GIMI
    # - ReShade
    #
    # Absolute paths to DLLs can also be used when prefixed with `dll:`
    modifications:
        - 3DMigoto # This value can also be inputted as 'GIMI'

    # Whether to disable the anti-cheat.
    #
    # Sometimes, the anti-cheat can prevent DLLs from being injected.
    # If this is the case, set this to `true`.
    #
    # In most cases however, this should be set to `false`.
    disable-anti-cheat: false

# Sniffer config
sniffer:
    # The name of the network interface to use.
    #
    # You will be asked to set this during the setup process.
    # Once it is set, you can change it here.
    device-name: ""

    # The packet capturing filter to use.
    #
    # If you don't know how to write filters, leave this default.
    # In most scenarios, you won't need to change this.
    filter: "udp portrange 22101-22102"

    # A list of ports that the server listens on.
    #
    # If you change the capture filter, you will likely need to change this too.
    # This is used for determining which side sent a packet. (client/server)
    server-ports:
        - 22101
        - 22102

    # The path to the 'known seeds' file.
    #
    # This file should be readable and writable.
    # It contains all encryption seeds used recently.
    seeds-file: "$APPDATA/sniffer/known-seeds.txt"
